### ISSUE TITLE
Missing folder icons

### ISSUE THREAD

**Issue by sAleksovski** [snwh/paper-icon-theme#73]
Some folder icons are missing in Pantheon Files (Documents, Videos in main view, Documents, Pictures and Videos in the sidebar) when they are the in the smallest size.

![Missing icons](https://cloud.githubusercontent.com/assets/7473800/11574998/23818c02-9a0f-11e5-96f7-70f3db53300b.png)

**Comment by snwh** [comment]
Yeah, I haven't gotten to adding the pictogram to some of the smaller folder icons yet.

**Comment by bil-elmoussaoui** [comment]
@sAleksovski This was fixed in the latest commit i guess =)

**Comment by sAleksovski** [comment]
@bil-elmoussaoui Not yet, the icon for Documents is still missing at the smallest size.
Also, the icons on the left are with different color than the folder icons.

![image](https://cloud.githubusercontent.com/assets/7473800/15364659/8bf80c70-1d1d-11e6-82e0-363d98192d94.png)

**Comment by bil-elmoussaoui** [comment]
Check this out ec755b89f0d3e308d76823c14c06b067141747a7, you have to wait until you receive the update i guess

**Comment by sAleksovski** [comment]
Documents icon is fixed.
